// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN-PTfcgWjcfBqg3hoS_kUPgDUyGVupv4',
    appId: '1:560013335902:web:a34204de8f5904c40483cf',
    messagingSenderId: '560013335902',
    projectId: 'olenka-98e26',
    authDomain: 'olenka-98e26.firebaseapp.com',
    storageBucket: 'olenka-98e26.firebasestorage.app',
    measurementId: 'G-LT2ZWXN0X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhJZoNL6qyQ2T6-gSfqHrmCccR2iUDY5w',
    appId: '1:560013335902:android:66e0ad32890debae0483cf',
    messagingSenderId: '560013335902',
    projectId: 'olenka-98e26',
    storageBucket: 'olenka-98e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr5uqXjosSW1hgKlOaaW4ofTXb_7CqxCw',
    appId: '1:560013335902:ios:45bd745362e4c39b0483cf',
    messagingSenderId: '560013335902',
    projectId: 'olenka-98e26',
    storageBucket: 'olenka-98e26.firebasestorage.app',
    iosBundleId: 'com.example.olenkaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr5uqXjosSW1hgKlOaaW4ofTXb_7CqxCw',
    appId: '1:560013335902:ios:45bd745362e4c39b0483cf',
    messagingSenderId: '560013335902',
    projectId: 'olenka-98e26',
    storageBucket: 'olenka-98e26.firebasestorage.app',
    iosBundleId: 'com.example.olenkaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN-PTfcgWjcfBqg3hoS_kUPgDUyGVupv4',
    appId: '1:560013335902:web:56802c124b78e0e40483cf',
    messagingSenderId: '560013335902',
    projectId: 'olenka-98e26',
    authDomain: 'olenka-98e26.firebaseapp.com',
    storageBucket: 'olenka-98e26.firebasestorage.app',
    measurementId: 'G-QL4Q74QNTX',
  );
}
