// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiz3O6oCfaMdk7x3e1_yYzCSyIG9v_-og',
    appId: '1:195364338272:web:d78454f9d06d5d1a832105',
    messagingSenderId: '195364338272',
    projectId: 'gabriel-d3995',
    authDomain: 'gabriel-d3995.firebaseapp.com',
    storageBucket: 'gabriel-d3995.firebasestorage.app',
    measurementId: 'G-VV2834VV3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3lw4h0j8aW8hPI9ErCQZSZNF61ixjuOY',
    appId: '1:195364338272:android:952280688264a7e8832105',
    messagingSenderId: '195364338272',
    projectId: 'gabriel-d3995',
    storageBucket: 'gabriel-d3995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaQ7TEmokaedxcEQvdaB5P4ZzZG3ZOV90',
    appId: '1:195364338272:ios:4e9eb18003dc80b7832105',
    messagingSenderId: '195364338272',
    projectId: 'gabriel-d3995',
    storageBucket: 'gabriel-d3995.firebasestorage.app',
    iosBundleId: 'com.example.gabrielClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaQ7TEmokaedxcEQvdaB5P4ZzZG3ZOV90',
    appId: '1:195364338272:ios:4e9eb18003dc80b7832105',
    messagingSenderId: '195364338272',
    projectId: 'gabriel-d3995',
    storageBucket: 'gabriel-d3995.firebasestorage.app',
    iosBundleId: 'com.example.gabrielClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiz3O6oCfaMdk7x3e1_yYzCSyIG9v_-og',
    appId: '1:195364338272:web:90ba1c84e7a43cb7832105',
    messagingSenderId: '195364338272',
    projectId: 'gabriel-d3995',
    authDomain: 'gabriel-d3995.firebaseapp.com',
    storageBucket: 'gabriel-d3995.firebasestorage.app',
    measurementId: 'G-VJFSJTDGCS',
  );
}
