name: brands
description: Temas e assets de marcas (white-label) do super_app.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ../design_system   # ajuste o path se a árvore for diferente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # assets por marca (opcional, se você tiver logos/imagens)
  assets:
    - assets/brand_acme/
    - assets/brand_beta/
  # fonts: (opcional)
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
