name: micro_app_home
description: Microapp Home para o super_app.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  # opcional, mas ajuda o analisador a saber que é projeto Flutter:
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core                # contrato MicroApp
  design_system:
    path: ../design_system       # ThemeExtension + widgets DS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # nada aqui por enquanto (sem assets)
