# ==============================================================================
#  EmersonX - Fase 3: Busca Global + Settings + About
#  Autor  : Emerson
#  Versao : 1.0
#
#  O QUE ESTE SCRIPT FAZ:
#    1. SearchPage    (/search)   - busca fuzzy nos 14 modulos com historico
#    2. SettingsPage  (/settings) - tema, idioma, escala de texto, modo dev
#    3. AboutPage     (/about)    - info do app, stack, versao, links
#    4. Atualiza AppRouter com as 3 novas rotas
#    5. Atualiza HomePage com botoes de acesso (AppBar actions)
#
#  COMO RODAR:
#    Coloque este arquivo dentro da pasta raiz do projeto Flutter
#    Ex: D:\Develop\Flutter\emersonx
#
#    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#    .\emersonx_fase3_search_settings_about.ps1
# ==============================================================================

$ErrorActionPreference = "Stop"
$ROOT = Get-Location
$LIB = "$ROOT\lib"

function Write-Section {
    param([string]$T)
    Write-Host ""
    Write-Host "  --------------------------------------------------" -ForegroundColor Cyan
    Write-Host "   $T" -ForegroundColor Cyan
    Write-Host "  --------------------------------------------------" -ForegroundColor Cyan
    Write-Host ""
}
function Write-Ok { param([string]$T) Write-Host "  [OK] $T" -ForegroundColor Green }
function Write-Step { param([string]$T) Write-Host "  [>>] $T" -ForegroundColor Yellow }
function Write-Warn { param([string]$T) Write-Host "  [!!] $T" -ForegroundColor Yellow }

function Ensure-Dir {
    param([string]$P)
    if (-not (Test-Path $P)) {
        New-Item -ItemType Directory -Path $P -Force | Out-Null
    }
}

function Write-Dart {
    param([string]$Path, [string[]]$Lines)
    Ensure-Dir (Split-Path $Path -Parent)
    $enc = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, ($Lines -join "`n"), $enc)
}

# Verifica se o projeto existe
if (-not (Test-Path "$LIB\main.dart")) {
    Write-Host ""
    Write-Host "  [ERRO] main.dart nao encontrado em $LIB" -ForegroundColor Red
    Write-Host "  Execute primeiro o script da Fase 2." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "  ==================================================" -ForegroundColor Cyan
Write-Host "   EmersonX - Fase 3: Search + Settings + About" -ForegroundColor Cyan
Write-Host "   $(Get-Date -Format 'dd/MM/yyyy HH:mm')" -ForegroundColor DarkGray
Write-Host "  ==================================================" -ForegroundColor Cyan

# -----------------------------------------------------------------------
# PASSO 1 - PASTAS
# -----------------------------------------------------------------------
Write-Section "PASSO 1/6 - Criando Pastas"

$pastas = @(
    # Search
    "$LIB\features\search\domain\entities",
    "$LIB\features\search\domain\repositories",
    "$LIB\features\search\domain\usecases",
    "$LIB\features\search\data\datasources",
    "$LIB\features\search\data\repositories",
    "$LIB\features\search\presentation\pages",
    "$LIB\features\search\presentation\cubit",
    "$LIB\features\search\presentation\widgets",
    # Settings
    "$LIB\features\settings\domain\entities",
    "$LIB\features\settings\domain\repositories",
    "$LIB\features\settings\domain\usecases",
    "$LIB\features\settings\data\datasources",
    "$LIB\features\settings\data\repositories",
    "$LIB\features\settings\presentation\pages",
    "$LIB\features\settings\presentation\cubit",
    "$LIB\features\settings\presentation\widgets",
    # About
    "$LIB\features\about\presentation\pages",
    "$LIB\features\about\presentation\widgets"
)
foreach ($p in $pastas) { Ensure-Dir $p }
Write-Ok "Pastas criadas"

# -----------------------------------------------------------------------
# PASSO 2 - ATUALIZAR APPROUTES
# -----------------------------------------------------------------------
Write-Section "PASSO 2/6 - Atualizando AppRoutes"

Write-Dart "$LIB\core\router\app_routes.dart" @(
    "abstract final class AppRoutes {",
    "  // Core",
    "  static const splash   = '/';",
    "  static const home     = '/home';",
    "  static const search   = '/search';",
    "  static const settings = '/settings';",
    "  static const about    = '/about';",
    "",
    "  // Modulos",
    "  static const designSystem  = '/design-system';",
    "  static const layout        = '/layout';",
    "  static const animations    = '/animations';",
    "  static const accessibility = '/accessibility';",
    "  static const multimedia    = '/multimedia';",
    "  static const maps          = '/maps';",
    "  static const sensors       = '/sensors';",
    "  static const connectivity  = '/connectivity';",
    "  static const social        = '/social';",
    "  static const regional      = '/regional';",
    "  static const routing       = '/routing';",
    "  static const di            = '/di';",
    "  static const ai            = '/ai';",
    "  static const testing       = '/testing';",
    "}"
)
Write-Ok "app_routes.dart atualizado"

# -----------------------------------------------------------------------
# PASSO 3 - SEARCH FEATURE
# -----------------------------------------------------------------------
Write-Section "PASSO 3/6 - Gerando SearchPage"

# Entidade SearchResult
Write-Dart "$LIB\features\search\domain\entities\search_result.dart" @(
    "import 'package:flutter/material.dart';",
    "",
    "class SearchResult {",
    "  const SearchResult({",
    "    required this.id,",
    "    required this.title,",
    "    required this.subtitle,",
    "    required this.route,",
    "    required this.icon,",
    "    required this.color,",
    "    this.breadcrumb = '',",
    "  });",
    "",
    "  final String id;",
    "  final String title;",
    "  final String subtitle;",
    "  final String route;",
    "  final IconData icon;",
    "  final Color color;",
    "  final String breadcrumb;",
    "",
    "  // Calcula score de similaridade com a query (0.0 a 1.0)",
    "  double score(String query) {",
    "    if (query.isEmpty) return 0;",
    "    final q = query.toLowerCase().trim();",
    "    final t = title.toLowerCase();",
    "    final s = subtitle.toLowerCase();",
    "    if (t == q) return 1.0;",
    "    if (t.startsWith(q)) return 0.9;",
    "    if (t.contains(q)) return 0.8;",
    "    if (s.contains(q)) return 0.6;",
    "    // Busca por palavras individuais",
    "    final words = q.split(' ').where((w) => w.isNotEmpty);",
    "    final matches = words.where((w) => t.contains(w) || s.contains(w)).length;",
    "    if (words.isEmpty) return 0;",
    "    return matches / words.length * 0.5;",
    "  }",
    "}"
)
Write-Ok "search_result.dart criado"

# Index de todos os modulos para busca
Write-Dart "$LIB\features\search\data\datasources\search_index.dart" @(
    "import 'package:flutter/material.dart';",
    "import '../../domain/entities/search_result.dart';",
    "import '../../../../core/router/app_routes.dart';",
    "import '../../../../design_system/tokens/app_colors.dart';",
    "",
    "abstract final class SearchIndex {",
    "  static const all = <SearchResult>[",
    "    // --- Core ---",
    "    SearchResult(",
    "      id: 'settings',",
    "      title: 'Configuracoes',",
    "      subtitle: 'Tema, idioma, escala de texto, modo dev',",
    "      route: AppRoutes.settings,",
    "      icon: Icons.settings_outlined,",
    "      color: AppColors.neutral600,",
    "      breadcrumb: 'App / Configuracoes',",
    "    ),",
    "    SearchResult(",
    "      id: 'about',",
    "      title: 'Sobre o App',",
    "      subtitle: 'Versao, stack, creditos, licencas',",
    "      route: AppRoutes.about,",
    "      icon: Icons.info_outline,",
    "      color: AppColors.neutral600,",
    "      breadcrumb: 'App / Sobre',",
    "    ),",
    "    // --- Design System ---",
    "    SearchResult(",
    "      id: 'design_system',",
    "      title: 'Design System',",
    "      subtitle: 'Catalogo de componentes e tokens',",
    "      route: AppRoutes.designSystem,",
    "      icon: Icons.palette_outlined,",
    "      color: AppColors.moduleDesignSystem,",
    "      breadcrumb: 'Modulos / Design System',",
    "    ),",
    "    // --- Layout ---",
    "    SearchResult(",
    "      id: 'layout',",
    "      title: 'Layout e Responsividade',",
    "      subtitle: 'AdaptiveLayout, Grid, Slivers, Flex',",
    "      route: AppRoutes.layout,",
    "      icon: Icons.dashboard_outlined,",
    "      color: AppColors.moduleLayout,",
    "      breadcrumb: 'Modulos / Layout',",
    "    ),",
    "    // --- Animacoes ---",
    "    SearchResult(",
    "      id: 'animations',",
    "      title: 'Animacoes',",
    "      subtitle: 'Implicit, Explicit, Hero, Rive, Lottie',",
    "      route: AppRoutes.animations,",
    "      icon: Icons.animation_outlined,",
    "      color: AppColors.moduleAnimations,",
    "      breadcrumb: 'Modulos / Animacoes',",
    "    ),",
    "    // --- Acessibilidade ---",
    "    SearchResult(",
    "      id: 'accessibility',",
    "      title: 'Acessibilidade',",
    "      subtitle: 'Semantics, TalkBack, contraste, A11y',",
    "      route: AppRoutes.accessibility,",
    "      icon: Icons.accessibility_new_outlined,",
    "      color: AppColors.moduleAccessibility,",
    "      breadcrumb: 'Modulos / Acessibilidade',",
    "    ),",
    "    // --- Multimidia ---",
    "    SearchResult(",
    "      id: 'multimedia',",
    "      title: 'Multimidia',",
    "      subtitle: 'Camera, audio, video, galeria',",
    "      route: AppRoutes.multimedia,",
    "      icon: Icons.perm_media_outlined,",
    "      color: AppColors.moduleMultimedia,",
    "      breadcrumb: 'Modulos / Multimidia',",
    "    ),",
    "    // --- Maps ---",
    "    SearchResult(",
    "      id: 'maps',",
    "      title: 'Maps',",
    "      subtitle: 'Google Maps, geolocalizacao, geocoding',",
    "      route: AppRoutes.maps,",
    "      icon: Icons.map_outlined,",
    "      color: AppColors.moduleMaps,",
    "      breadcrumb: 'Modulos / Maps',",
    "    ),",
    "    // --- Sensores ---",
    "    SearchResult(",
    "      id: 'sensors',",
    "      title: 'Sensores',",
    "      subtitle: 'Acelerometro, giroscopio, bussola, luz',",
    "      route: AppRoutes.sensors,",
    "      icon: Icons.sensors_outlined,",
    "      color: AppColors.moduleSensors,",
    "      breadcrumb: 'Modulos / Sensores',",
    "    ),",
    "    // --- Conectividade ---",
    "    SearchResult(",
    "      id: 'connectivity',",
    "      title: 'Conectividade',",
    "      subtitle: 'Bluetooth, WiFi, NFC, WebSocket',",
    "      route: AppRoutes.connectivity,",
    "      icon: Icons.wifi_outlined,",
    "      color: AppColors.moduleConnectivity,",
    "      breadcrumb: 'Modulos / Conectividade',",
    "    ),",
    "    // --- Social ---",
    "    SearchResult(",
    "      id: 'social',",
    "      title: 'Social e Auth',",
    "      subtitle: 'Login, Google Sign-In, perfil, share',",
    "      route: AppRoutes.social,",
    "      icon: Icons.people_outline,",
    "      color: AppColors.moduleSocial,",
    "      breadcrumb: 'Modulos / Social',",
    "    ),",
    "    // --- Regional ---",
    "    SearchResult(",
    "      id: 'regional',",
    "      title: 'Regionalizacao',",
    "      subtitle: 'i18n PT/EN/ES/JA, formatos, RTL',",
    "      route: AppRoutes.regional,",
    "      icon: Icons.language_outlined,",
    "      color: AppColors.moduleRegional,",
    "      breadcrumb: 'Modulos / Regionalizacao',",
    "    ),",
    "    // --- Rotas ---",
    "    SearchResult(",
    "      id: 'routing',",
    "      title: 'Rotas e Transicoes',",
    "      subtitle: 'GoRouter, transicoes, deep links, guards',",
    "      route: AppRoutes.routing,",
    "      icon: Icons.route_outlined,",
    "      color: AppColors.moduleRouting,",
    "      breadcrumb: 'Modulos / Rotas',",
    "    ),",
    "    // --- DI ---",
    "    SearchResult(",
    "      id: 'di',",
    "      title: 'Injecao de Dependencia',",
    "      subtitle: 'get_it, injectable, scopes, lifetimes',",
    "      route: AppRoutes.di,",
    "      icon: Icons.hub_outlined,",
    "      color: AppColors.moduleDI,",
    "      breadcrumb: 'Modulos / DI',",
    "    ),",
    "    // --- IA ---",
    "    SearchResult(",
    "      id: 'ai',",
    "      title: 'Inteligencia Artificial',",
    "      subtitle: 'Gemini, visao computacional, TTS, STT',",
    "      route: AppRoutes.ai,",
    "      icon: Icons.smart_toy_outlined,",
    "      color: AppColors.moduleAI,",
    "      breadcrumb: 'Modulos / IA',",
    "    ),",
    "    // --- Testes ---",
    "    SearchResult(",
    "      id: 'testing',",
    "      title: 'Testes',",
    "      subtitle: 'Unit, Widget, Integration, Coverage',",
    "      route: AppRoutes.testing,",
    "      icon: Icons.bug_report_outlined,",
    "      color: AppColors.moduleTesting,",
    "      breadcrumb: 'Modulos / Testes',",
    "    ),",
    "  ];",
    "}"
)
Write-Ok "search_index.dart criado"

# SearchCubit
Write-Dart "$LIB\features\search\presentation\cubit\search_cubit.dart" @(
    "import 'package:flutter_bloc/flutter_bloc.dart';",
    "import '../../domain/entities/search_result.dart';",
    "import '../../data/datasources/search_index.dart';",
    "import 'search_state.dart';",
    "",
    "class SearchCubit extends Cubit<SearchState> {",
    "  SearchCubit() : super(const SearchIdle());",
    "",
    "  // Historico em memoria (max 8 itens)",
    "  final List<SearchResult> _history = [];",
    "  List<SearchResult> get history => List.unmodifiable(_history);",
    "",
    "  void search(String query) {",
    "    final q = query.trim();",
    "    if (q.isEmpty) {",
    "      emit(const SearchIdle());",
    "      return;",
    "    }",
    "",
    "    // Filtra e ordena pelo score",
    "    final results = SearchIndex.all",
    "        .map((r) => _ScoredResult(r, r.score(q)))",
    "        .where((s) => s.score > 0)",
    "        .toList()",
    "      ..sort((a, b) => b.score.compareTo(a.score));",
    "",
    "    final found = results.map((s) => s.result).toList();",
    "    emit(SearchResults(query: q, results: found));",
    "  }",
    "",
    "  void clear() => emit(const SearchIdle());",
    "",
    "  void addToHistory(SearchResult result) {",
    "    _history.removeWhere((r) => r.id == result.id);",
    "    _history.insert(0, result);",
    "    if (_history.length > 8) _history.removeLast();",
    "    // Re-emite o estado atual com historico atualizado",
    "    final current = state;",
    "    if (current is SearchIdle) emit(const SearchIdle());",
    "  }",
    "",
    "  void removeFromHistory(String id) {",
    "    _history.removeWhere((r) => r.id == id);",
    "    emit(const SearchIdle());",
    "  }",
    "}",
    "",
    "class _ScoredResult {",
    "  const _ScoredResult(this.result, this.score);",
    "  final SearchResult result;",
    "  final double score;",
    "}"
)
Write-Ok "search_cubit.dart criado"

Write-Dart "$LIB\features\search\presentation\cubit\search_state.dart" @(
    "import '../../domain/entities/search_result.dart';",
    "",
    "abstract class SearchState {",
    "  const SearchState();",
    "}",
    "",
    "class SearchIdle extends SearchState {",
    "  const SearchIdle();",
    "}",
    "",
    "class SearchResults extends SearchState {",
    "  const SearchResults({required this.query, required this.results});",
    "  final String query;",
    "  final List<SearchResult> results;",
    "  bool get isEmpty => results.isEmpty;",
    "}"
)
Write-Ok "search_state.dart criado"

# SearchResultTile widget
Write-Dart "$LIB\features\search\presentation\widgets\search_result_tile.dart" @(
    "import 'package:flutter/material.dart';",
    "import '../../domain/entities/search_result.dart';",
    "import '../../../../design_system/tokens/tokens.dart';",
    "",
    "class SearchResultTile extends StatelessWidget {",
    "  const SearchResultTile({",
    "    super.key,",
    "    required this.result,",
    "    required this.query,",
    "    required this.onTap,",
    "  });",
    "",
    "  final SearchResult result;",
    "  final String query;",
    "  final VoidCallback onTap;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final isDark = Theme.of(context).brightness == Brightness.dark;",
    "",
    "    return InkWell(",
    "      onTap: onTap,",
    "      borderRadius: BorderRadius.circular(AppRadius.md),",
    "      child: Padding(",
    "        padding: const EdgeInsets.symmetric(",
    "          horizontal: AppSpacing.md,",
    "          vertical: AppSpacing.sm,",
    "        ),",
    "        child: Row(",
    "          children: [",
    "            // Icone colorido",
    "            Container(",
    "              width: 40,",
    "              height: 40,",
    "              decoration: BoxDecoration(",
    "                color: result.color.withOpacity(0.12),",
    "                borderRadius: BorderRadius.circular(AppRadius.sm),",
    "              ),",
    "              child: Icon(result.icon, color: result.color, size: 20),",
    "            ),",
    "            const SizedBox(width: AppSpacing.md),",
    "            // Textos",
    "            Expanded(",
    "              child: Column(",
    "                crossAxisAlignment: CrossAxisAlignment.start,",
    "                children: [",
    "                  _HighlightText(",
    "                    text: result.title,",
    "                    query: query,",
    "                    style: AppTextStyles.labelLarge.copyWith(",
    "                      color: isDark ? AppColors.white : AppColors.neutral900,",
    "                    ),",
    "                    highlightColor: result.color,",
    "                  ),",
    "                  const SizedBox(height: 2),",
    "                  Text(",
    "                    result.breadcrumb,",
    "                    style: AppTextStyles.labelSmall.copyWith(",
    "                      color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "                    ),",
    "                  ),",
    "                ],",
    "              ),",
    "            ),",
    "            Icon(",
    "              Icons.arrow_forward_ios_rounded,",
    "              size: 14,",
    "              color: isDark ? AppColors.neutral400 : AppColors.neutral400,",
    "            ),",
    "          ],",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "// Widget que destaca a query no texto",
    "class _HighlightText extends StatelessWidget {",
    "  const _HighlightText({",
    "    required this.text,",
    "    required this.query,",
    "    required this.style,",
    "    required this.highlightColor,",
    "  });",
    "",
    "  final String text;",
    "  final String query;",
    "  final TextStyle style;",
    "  final Color highlightColor;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    if (query.isEmpty) return Text(text, style: style);",
    "",
    "    final lower = text.toLowerCase();",
    "    final q = query.toLowerCase();",
    "    final idx = lower.indexOf(q);",
    "",
    "    if (idx == -1) return Text(text, style: style);",
    "",
    "    return RichText(",
    "      text: TextSpan(",
    "        children: [",
    "          if (idx > 0)",
    "            TextSpan(text: text.substring(0, idx), style: style),",
    "          TextSpan(",
    "            text: text.substring(idx, idx + q.length),",
    "            style: style.copyWith(",
    "              color: highlightColor,",
    "              fontWeight: FontWeight.w700,",
    "              backgroundColor: highlightColor.withOpacity(0.1),",
    "            ),",
    "          ),",
    "          TextSpan(",
    "            text: text.substring(idx + q.length),",
    "            style: style,",
    "          ),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "}"
)
Write-Ok "search_result_tile.dart criado"

# SearchPage
Write-Dart "$LIB\features\search\presentation\pages\search_page.dart" @(
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_bloc/flutter_bloc.dart';",
    "import 'package:go_router/go_router.dart';",
    "import '../../../../design_system/tokens/tokens.dart';",
    "import '../cubit/search_cubit.dart';",
    "import '../cubit/search_state.dart';",
    "import '../widgets/search_result_tile.dart';",
    "import '../../domain/entities/search_result.dart';",
    "",
    "class SearchPage extends StatelessWidget {",
    "  const SearchPage({super.key});",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return BlocProvider(",
    "      create: (_) => SearchCubit(),",
    "      child: const _SearchView(),",
    "    );",
    "  }",
    "}",
    "",
    "class _SearchView extends StatefulWidget {",
    "  const _SearchView();",
    "  @override",
    "  State<_SearchView> createState() => _SearchViewState();",
    "}",
    "",
    "class _SearchViewState extends State<_SearchView> {",
    "  final _controller = TextEditingController();",
    "  final _focus = FocusNode();",
    "",
    "  @override",
    "  void initState() {",
    "    super.initState();",
    "    // Abre o teclado automaticamente",
    "    WidgetsBinding.instance.addPostFrameCallback((_) => _focus.requestFocus());",
    "  }",
    "",
    "  @override",
    "  void dispose() {",
    "    _controller.dispose();",
    "    _focus.dispose();",
    "    super.dispose();",
    "  }",
    "",
    "  void _onChanged(BuildContext context, String value) {",
    "    context.read<SearchCubit>().search(value);",
    "  }",
    "",
    "  void _onSelect(BuildContext context, SearchResult result) {",
    "    context.read<SearchCubit>().addToHistory(result);",
    "    context.go(result.route);",
    "  }",
    "",
    "  void _onClear(BuildContext context) {",
    "    _controller.clear();",
    "    context.read<SearchCubit>().clear();",
    "    _focus.requestFocus();",
    "  }",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final isDark = Theme.of(context).brightness == Brightness.dark;",
    "    final scheme = Theme.of(context).colorScheme;",
    "    final bgColor = isDark ? AppColors.dark800 : AppColors.white;",
    "    final fieldBg = isDark ? AppColors.dark700 : AppColors.neutral100;",
    "    final hintColor = isDark ? AppColors.neutral400 : AppColors.neutral600;",
    "",
    "    return Scaffold(",
    "      backgroundColor: isDark ? AppColors.dark900 : AppColors.neutral50,",
    "      body: SafeArea(",
    "        child: Column(",
    "          children: [",
    "            // Barra de busca no topo",
    "            Container(",
    "              color: bgColor,",
    "              padding: const EdgeInsets.fromLTRB(",
    "                AppSpacing.md, AppSpacing.sm,",
    "                AppSpacing.md, AppSpacing.md,",
    "              ),",
    "              child: Row(",
    "                children: [",
    "                  // Botao voltar",
    "                  GestureDetector(",
    "                    onTap: () => context.pop(),",
    "                    child: Icon(",
    "                      Icons.arrow_back_ios_new_rounded,",
    "                      size: 20,",
    "                      color: isDark ? AppColors.white : AppColors.neutral900,",
    "                    ),",
    "                  ),",
    "                  const SizedBox(width: AppSpacing.md),",
    "                  // Campo de texto",
    "                  Expanded(",
    "                    child: Container(",
    "                      height: 46,",
    "                      decoration: BoxDecoration(",
    "                        color: fieldBg,",
    "                        borderRadius: BorderRadius.circular(AppRadius.md),",
    "                      ),",
    "                      child: Row(",
    "                        children: [",
    "                          const SizedBox(width: AppSpacing.md),",
    "                          Icon(Icons.search_rounded, size: 20, color: hintColor),",
    "                          const SizedBox(width: AppSpacing.xs),",
    "                          Expanded(",
    "                            child: TextField(",
    "                              controller: _controller,",
    "                              focusNode: _focus,",
    "                              onChanged: (v) => _onChanged(context, v),",
    "                              style: AppTextStyles.bodyMedium.copyWith(",
    "                                color: isDark ? AppColors.white : AppColors.neutral900,",
    "                              ),",
    "                              decoration: InputDecoration(",
    "                                hintText: 'Buscar modulos e telas...',",
    "                                hintStyle: AppTextStyles.bodyMedium.copyWith(",
    "                                  color: hintColor,",
    "                                ),",
    "                                border: InputBorder.none,",
    "                                contentPadding: EdgeInsets.zero,",
    "                                isDense: true,",
    "                              ),",
    "                            ),",
    "                          ),",
    "                          // Botao limpar",
    "                          BlocBuilder<SearchCubit, SearchState>(",
    "                            builder: (context, state) {",
    "                              if (state is! SearchResults) {",
    "                                return const SizedBox(width: AppSpacing.md);",
    "                              }",
    "                              return GestureDetector(",
    "                                onTap: () => _onClear(context),",
    "                                child: Padding(",
    "                                  padding: const EdgeInsets.symmetric(",
    "                                    horizontal: AppSpacing.sm,",
    "                                  ),",
    "                                  child: Icon(",
    "                                    Icons.close_rounded,",
    "                                    size: 18,",
    "                                    color: hintColor,",
    "                                  ),",
    "                                ),",
    "                              );",
    "                            },",
    "                          ),",
    "                        ],",
    "                      ),",
    "                    ),",
    "                  ),",
    "                ],",
    "              ),",
    "            ),",
    "",
    "            // Conteudo",
    "            Expanded(",
    "              child: BlocBuilder<SearchCubit, SearchState>(",
    "                builder: (context, state) {",
    "                  final cubit = context.read<SearchCubit>();",
    "",
    "                  // Estado inicial: mostrar historico",
    "                  if (state is SearchIdle) {",
    "                    if (cubit.history.isEmpty) {",
    "                      return _EmptyHint(isDark: isDark);",
    "                    }",
    "                    return _HistoryList(",
    "                      history: cubit.history,",
    "                      isDark: isDark,",
    "                      onTap: (r) => _onSelect(context, r),",
    "                      onRemove: (id) => cubit.removeFromHistory(id),",
    "                    );",
    "                  }",
    "",
    "                  // Sem resultados",
    "                  if (state is SearchResults && state.isEmpty) {",
    "                    return _NoResults(query: state.query, isDark: isDark);",
    "                  }",
    "",
    "                  // Lista de resultados",
    "                  if (state is SearchResults) {",
    "                    return _ResultsList(",
    "                      results: state.results,",
    "                      query: state.query,",
    "                      isDark: isDark,",
    "                      bgColor: bgColor,",
    "                      onTap: (r) => _onSelect(context, r),",
    "                    );",
    "                  }",
    "",
    "                  return const SizedBox.shrink();",
    "                },",
    "              ),",
    "            ),",
    "          ],",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "// ---- Widgets internos ----",
    "",
    "class _EmptyHint extends StatelessWidget {",
    "  const _EmptyHint({required this.isDark});",
    "  final bool isDark;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Center(",
    "      child: Column(",
    "        mainAxisAlignment: MainAxisAlignment.center,",
    "        children: [",
    "          Icon(",
    "            Icons.search_rounded,",
    "            size: 64,",
    "            color: isDark ? AppColors.dark600 : AppColors.neutral200,",
    "          ),",
    "          const SizedBox(height: AppSpacing.md),",
    "          Text(",
    "            'Digite para buscar modulos',",
    "            style: AppTextStyles.bodyMedium.copyWith(",
    "              color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "            ),",
    "          ),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "class _NoResults extends StatelessWidget {",
    "  const _NoResults({required this.query, required this.isDark});",
    "  final String query;",
    "  final bool isDark;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Center(",
    "      child: Column(",
    "        mainAxisAlignment: MainAxisAlignment.center,",
    "        children: [",
    "          Icon(",
    "            Icons.search_off_rounded,",
    "            size: 64,",
    "            color: isDark ? AppColors.dark600 : AppColors.neutral200,",
    "          ),",
    "          const SizedBox(height: AppSpacing.md),",
    "          Text(",
    "            'Nada encontrado para',",
    "            style: AppTextStyles.bodyMedium.copyWith(",
    "              color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "            ),",
    "          ),",
    "          const SizedBox(height: AppSpacing.xxs),",
    "          Text(",
    ('            ' + "'" + '"' + '$query"' + "',"),
    "            style: AppTextStyles.titleMedium.copyWith(",
    "              color: isDark ? AppColors.white : AppColors.neutral900,",
    "            ),",
    "          ),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "class _ResultsList extends StatelessWidget {",
    "  const _ResultsList({",
    "    required this.results,",
    "    required this.query,",
    "    required this.isDark,",
    "    required this.bgColor,",
    "    required this.onTap,",
    "  });",
    "  final List<SearchResult> results;",
    "  final String query;",
    "  final bool isDark;",
    "  final Color bgColor;",
    "  final void Function(SearchResult) onTap;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Column(",
    "      crossAxisAlignment: CrossAxisAlignment.start,",
    "      children: [",
    "        Padding(",
    "          padding: const EdgeInsets.fromLTRB(AppSpacing.md, AppSpacing.md, 0, AppSpacing.xs),",
    "          child: Text(",
    "            '${results.length} resultado${results.length != 1 ? 's' : ''}',",
    "            style: AppTextStyles.labelSmall.copyWith(",
    "              color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "              letterSpacing: 0.5,",
    "            ),",
    "          ),",
    "        ),",
    "        Expanded(",
    "          child: Container(",
    "            color: bgColor,",
    "            child: ListView.separated(",
    "              itemCount: results.length,",
    "              separatorBuilder: (_, __) => Divider(",
    "                height: 1,",
    "                indent: 72,",
    "                color: isDark ? AppColors.dark600 : AppColors.neutral200,",
    "              ),",
    "              itemBuilder: (context, i) => SearchResultTile(",
    "                result: results[i],",
    "                query: query,",
    "                onTap: () => onTap(results[i]),",
    "              ),",
    "            ),",
    "          ),",
    "        ),",
    "      ],",
    "    );",
    "  }",
    "}",
    "",
    "class _HistoryList extends StatelessWidget {",
    "  const _HistoryList({",
    "    required this.history,",
    "    required this.isDark,",
    "    required this.onTap,",
    "    required this.onRemove,",
    "  });",
    "  final List<SearchResult> history;",
    "  final bool isDark;",
    "  final void Function(SearchResult) onTap;",
    "  final void Function(String) onRemove;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final bgColor = isDark ? AppColors.dark800 : AppColors.white;",
    "    return Column(",
    "      crossAxisAlignment: CrossAxisAlignment.start,",
    "      children: [",
    "        Padding(",
    "          padding: const EdgeInsets.fromLTRB(AppSpacing.md, AppSpacing.md, 0, AppSpacing.xs),",
    "          child: Text(",
    "            'Recentes',",
    "            style: AppTextStyles.labelSmall.copyWith(",
    "              color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "              letterSpacing: 0.5,",
    "            ),",
    "          ),",
    "        ),",
    "        Expanded(",
    "          child: Container(",
    "            color: bgColor,",
    "            child: ListView.separated(",
    "              itemCount: history.length,",
    "              separatorBuilder: (_, __) => Divider(",
    "                height: 1,",
    "                indent: 72,",
    "                color: isDark ? AppColors.dark600 : AppColors.neutral200,",
    "              ),",
    "              itemBuilder: (context, i) {",
    "                final r = history[i];",
    "                return Dismissible(",
    "                  key: ValueKey(r.id),",
    "                  direction: DismissDirection.endToStart,",
    "                  background: Container(",
    "                    color: AppColors.error.withOpacity(0.1),",
    "                    alignment: Alignment.centerRight,",
    "                    padding: const EdgeInsets.only(right: AppSpacing.lg),",
    "                    child: const Icon(Icons.delete_outline, color: AppColors.error),",
    "                  ),",
    "                  onDismissed: (_) => onRemove(r.id),",
    "                  child: SearchResultTile(",
    "                    result: r,",
    "                    query: '',",
    "                    onTap: () => onTap(r),",
    "                  ),",
    "                );",
    "              },",
    "            ),",
    "          ),",
    "        ),",
    "      ],",
    "    );",
    "  }",
    "}"
)
Write-Ok "search_page.dart criado"

# -----------------------------------------------------------------------
# PASSO 4 - SETTINGS FEATURE
# -----------------------------------------------------------------------
Write-Section "PASSO 4/6 - Gerando SettingsPage"

# SettingsEntity
Write-Dart "$LIB\features\settings\domain\entities\app_settings.dart" @(
    "import 'package:flutter/material.dart';",
    "",
    "class AppSettings {",
    "  const AppSettings({",
    "    this.themeMode = ThemeMode.system,",
    "    this.textScaleFactor = 1.0,",
    "    this.showPerformanceOverlay = false,",
    "    this.showGridOverlay = false,",
    "    this.enableDevMode = false,",
    "  });",
    "",
    "  final ThemeMode themeMode;",
    "  final double textScaleFactor;",
    "  final bool showPerformanceOverlay;",
    "  final bool showGridOverlay;",
    "  final bool enableDevMode;",
    "",
    "  AppSettings copyWith({",
    "    ThemeMode? themeMode,",
    "    double? textScaleFactor,",
    "    bool? showPerformanceOverlay,",
    "    bool? showGridOverlay,",
    "    bool? enableDevMode,",
    "  }) {",
    "    return AppSettings(",
    "      themeMode: themeMode ?? this.themeMode,",
    "      textScaleFactor: textScaleFactor ?? this.textScaleFactor,",
    "      showPerformanceOverlay: showPerformanceOverlay ?? this.showPerformanceOverlay,",
    "      showGridOverlay: showGridOverlay ?? this.showGridOverlay,",
    "      enableDevMode: enableDevMode ?? this.enableDevMode,",
    "    );",
    "  }",
    "}"
)
Write-Ok "app_settings.dart criado"

# SettingsCubit
Write-Dart "$LIB\features\settings\presentation\cubit\settings_cubit.dart" @(
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_bloc/flutter_bloc.dart';",
    "import '../../domain/entities/app_settings.dart';",
    "",
    "class SettingsCubit extends Cubit<AppSettings> {",
    "  SettingsCubit() : super(const AppSettings());",
    "",
    "  void setTheme(ThemeMode mode) => emit(state.copyWith(themeMode: mode));",
    "",
    "  void setTextScale(double scale) {",
    "    final clamped = scale.clamp(0.8, 1.4);",
    "    emit(state.copyWith(textScaleFactor: clamped));",
    "  }",
    "",
    "  void togglePerformanceOverlay() => emit(",
    "    state.copyWith(showPerformanceOverlay: !state.showPerformanceOverlay),",
    "  );",
    "",
    "  void toggleGridOverlay() => emit(",
    "    state.copyWith(showGridOverlay: !state.showGridOverlay),",
    "  );",
    "",
    "  void toggleDevMode() => emit(",
    "    state.copyWith(enableDevMode: !state.enableDevMode),",
    "  );",
    "",
    "  void reset() => emit(const AppSettings());",
    "}"
)
Write-Ok "settings_cubit.dart criado"

# SettingsTile widget
Write-Dart "$LIB\features\settings\presentation\widgets\settings_tile.dart" @(
    "import 'package:flutter/material.dart';",
    "import '../../../../design_system/tokens/tokens.dart';",
    "",
    "class SettingsTile extends StatelessWidget {",
    "  const SettingsTile({",
    "    super.key,",
    "    required this.title,",
    "    this.subtitle,",
    "    required this.icon,",
    "    this.trailing,",
    "    this.onTap,",
    "    this.iconColor,",
    "  });",
    "",
    "  final String title;",
    "  final String? subtitle;",
    "  final IconData icon;",
    "  final Widget? trailing;",
    "  final VoidCallback? onTap;",
    "  final Color? iconColor;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final isDark = Theme.of(context).brightness == Brightness.dark;",
    "    final ic = iconColor ?? (isDark ? AppColors.neutral400 : AppColors.neutral600);",
    "",
    "    return InkWell(",
    "      onTap: onTap,",
    "      child: Padding(",
    "        padding: const EdgeInsets.symmetric(",
    "          horizontal: AppSpacing.md,",
    "          vertical: AppSpacing.md,",
    "        ),",
    "        child: Row(",
    "          children: [",
    "            Icon(icon, size: 22, color: ic),",
    "            const SizedBox(width: AppSpacing.md),",
    "            Expanded(",
    "              child: Column(",
    "                crossAxisAlignment: CrossAxisAlignment.start,",
    "                children: [",
    "                  Text(",
    "                    title,",
    "                    style: AppTextStyles.bodyMedium.copyWith(",
    "                      color: isDark ? AppColors.white : AppColors.neutral900,",
    "                      fontWeight: FontWeight.w500,",
    "                    ),",
    "                  ),",
    "                  if (subtitle != null) ...[",
    "                    const SizedBox(height: 2),",
    "                    Text(",
    "                      subtitle!,",
    "                      style: AppTextStyles.labelSmall.copyWith(",
    "                        color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "                      ),",
    "                    ),",
    "                  ],",
    "                ],",
    "              ),",
    "            ),",
    "            if (trailing != null) trailing!,",
    "          ],",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "class SettingsSection extends StatelessWidget {",
    "  const SettingsSection({",
    "    super.key,",
    "    required this.title,",
    "    required this.children,",
    "  });",
    "",
    "  final String title;",
    "  final List<Widget> children;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final isDark = Theme.of(context).brightness == Brightness.dark;",
    "    final cardBg = isDark ? AppColors.dark800 : AppColors.white;",
    "    final border = isDark ? AppColors.dark600 : AppColors.neutral200;",
    "",
    "    return Column(",
    "      crossAxisAlignment: CrossAxisAlignment.start,",
    "      children: [",
    "        Padding(",
    "          padding: const EdgeInsets.fromLTRB(AppSpacing.md, AppSpacing.lg, 0, AppSpacing.xs),",
    "          child: Text(",
    "            title.toUpperCase(),",
    "            style: AppTextStyles.labelSmall.copyWith(",
    "              color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "              letterSpacing: 1.0,",
    "            ),",
    "          ),",
    "        ),",
    "        Container(",
    "          decoration: BoxDecoration(",
    "            color: cardBg,",
    "            border: Border(",
    "              top: BorderSide(color: border),",
    "              bottom: BorderSide(color: border),",
    "            ),",
    "          ),",
    "          child: Column(",
    "            children: children.indexed.map((entry) {",
    "              final i = entry.$1;",
    "              final w = entry.$2;",
    "              if (i == children.length - 1) return w;",
    "              return Column(",
    "                children: [",
    "                  w,",
    "                  Divider(",
    "                    height: 1,",
    "                    indent: 54,",
    "                    color: border,",
    "                  ),",
    "                ],",
    "              );",
    "            }).toList(),",
    "          ),",
    "        ),",
    "      ],",
    "    );",
    "  }",
    "}"
)
Write-Ok "settings_tile.dart criado"

# SettingsPage
Write-Dart "$LIB\features\settings\presentation\pages\settings_page.dart" @(
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_bloc/flutter_bloc.dart';",
    "import '../../../../design_system/tokens/tokens.dart';",
    "import '../../../../core/di/theme_cubit.dart';",
    "import '../cubit/settings_cubit.dart';",
    "import '../../domain/entities/app_settings.dart';",
    "import '../widgets/settings_tile.dart';",
    "",
    "class SettingsPage extends StatelessWidget {",
    "  const SettingsPage({super.key});",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return BlocProvider(",
    "      create: (_) => SettingsCubit(),",
    "      child: const _SettingsView(),",
    "    );",
    "  }",
    "}",
    "",
    "class _SettingsView extends StatelessWidget {",
    "  const _SettingsView();",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final isDark = Theme.of(context).brightness == Brightness.dark;",
    "    final scaffoldBg = isDark ? AppColors.dark900 : AppColors.neutral50;",
    "",
    "    return Scaffold(",
    "      backgroundColor: scaffoldBg,",
    "      appBar: AppBar(",
    "        title: Text(",
    "          'Configuracoes',",
    "          style: AppTextStyles.titleMedium.copyWith(",
    "            color: isDark ? AppColors.white : AppColors.neutral900,",
    "          ),",
    "        ),",
    "        backgroundColor: isDark ? AppColors.dark800 : AppColors.white,",
    "      ),",
    "      body: BlocBuilder<SettingsCubit, AppSettings>(",
    "        builder: (context, settings) {",
    "          final cubit = context.read<SettingsCubit>();",
    "          return ListView(",
    "            children: [",
    "",
    "              // --- APARENCIA ---",
    "              SettingsSection(",
    "                title: 'Aparencia',",
    "                children: [",
    "                  SettingsTile(",
    "                    icon: Icons.dark_mode_outlined,",
    "                    title: 'Tema',",
    "                    subtitle: _themeLabel(settings.themeMode),",
    "                    trailing: _ThemeSegmented(",
    "                      current: settings.themeMode,",
    "                      onChange: (m) {",
    "                        cubit.setTheme(m);",
    "                        context.read<ThemeCubit>().emit(m);",
    "                      },",
    "                    ),",
    "                  ),",
    "                  SettingsTile(",
    "                    icon: Icons.text_fields_rounded,",
    "                    title: 'Escala de texto',",
    "                    subtitle: '${(settings.textScaleFactor * 100).round()}%',",
    "                    trailing: SizedBox(",
    "                      width: 160,",
    "                      child: Slider(",
    "                        value: settings.textScaleFactor,",
    "                        min: 0.8,",
    "                        max: 1.4,",
    "                        divisions: 6,",
    "                        label: '${(settings.textScaleFactor * 100).round()}%',",
    "                        onChanged: cubit.setTextScale,",
    "                      ),",
    "                    ),",
    "                  ),",
    "                ],",
    "              ),",
    "",
    "              // --- DESENVOLVEDOR ---",
    "              SettingsSection(",
    "                title: 'Desenvolvedor',",
    "                children: [",
    "                  SettingsTile(",
    "                    icon: Icons.code_rounded,",
    "                    title: 'Modo desenvolvedor',",
    "                    subtitle: 'Ativa opcoes avancadas',",
    "                    iconColor: AppColors.primary,",
    "                    trailing: Switch(",
    "                      value: settings.enableDevMode,",
    "                      onChanged: (_) => cubit.toggleDevMode(),",
    "                    ),",
    "                  ),",
    "                  if (settings.enableDevMode) ...[",
    "                    SettingsTile(",
    "                      icon: Icons.speed_rounded,",
    "                      title: 'Performance overlay',",
    "                      subtitle: 'Exibe FPS e rasterizacao',",
    "                      trailing: Switch(",
    "                        value: settings.showPerformanceOverlay,",
    "                        onChanged: (_) => cubit.togglePerformanceOverlay(),",
    "                      ),",
    "                    ),",
    "                    SettingsTile(",
    "                      icon: Icons.grid_4x4_rounded,",
    "                      title: 'Grid overlay',",
    "                      subtitle: 'Exibe grade de layout',",
    "                      trailing: Switch(",
    "                        value: settings.showGridOverlay,",
    "                        onChanged: (_) => cubit.toggleGridOverlay(),",
    "                      ),",
    "                    ),",
    "                  ],",
    "                ],",
    "              ),",
    "",
    "              // --- SOBRE ---",
    "              SettingsSection(",
    "                title: 'App',",
    "                children: [",
    "                  SettingsTile(",
    "                    icon: Icons.info_outline,",
    "                    title: 'Versao',",
    "                    subtitle: '1.0.0 (build 1)',",
    "                    trailing: const Icon(Icons.arrow_forward_ios_rounded, size: 14),",
    "                  ),",
    "                  SettingsTile(",
    "                    icon: Icons.restore_rounded,",
    "                    title: 'Restaurar padroes',",
    "                    subtitle: 'Redefine todas as configuracoes',",
    "                    iconColor: AppColors.error,",
    "                    onTap: () => _showResetDialog(context, cubit),",
    "                  ),",
    "                ],",
    "              ),",
    "",
    "              const SizedBox(height: AppSpacing.xxxl),",
    "            ],",
    "          );",
    "        },",
    "      ),",
    "    );",
    "  }",
    "",
    "  String _themeLabel(ThemeMode m) => switch (m) {",
    "    ThemeMode.light  => 'Claro',",
    "    ThemeMode.dark   => 'Escuro',",
    "    ThemeMode.system => 'Sistema',",
    "  };",
    "",
    "  void _showResetDialog(BuildContext context, SettingsCubit cubit) {",
    "    showDialog<void>(",
    "      context: context,",
    "      builder: (_) => AlertDialog(",
    "        title: const Text('Restaurar padroes?'),",
    "        content: const Text('Todas as configuracoes serao redefinidas.'),",
    "        actions: [",
    "          TextButton(",
    "            onPressed: () => Navigator.pop(context),",
    "            child: const Text('Cancelar'),",
    "          ),",
    "          TextButton(",
    "            onPressed: () { cubit.reset(); Navigator.pop(context); },",
    "            child: Text('Restaurar', style: TextStyle(color: AppColors.error)),",
    "          ),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "// Segmented button para selecao de tema",
    "class _ThemeSegmented extends StatelessWidget {",
    "  const _ThemeSegmented({required this.current, required this.onChange});",
    "  final ThemeMode current;",
    "  final void Function(ThemeMode) onChange;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return SegmentedButton<ThemeMode>(",
    "      showSelectedIcon: false,",
    "      style: const ButtonStyle(visualDensity: VisualDensity.compact),",
    "      segments: const [",
    "        ButtonSegment(value: ThemeMode.light,  icon: Icon(Icons.light_mode_outlined, size: 16)),",
    "        ButtonSegment(value: ThemeMode.system, icon: Icon(Icons.brightness_auto,     size: 16)),",
    "        ButtonSegment(value: ThemeMode.dark,   icon: Icon(Icons.dark_mode_outlined,  size: 16)),",
    "      ],",
    "      selected: {current},",
    "      onSelectionChanged: (s) => onChange(s.first),",
    "    );",
    "  }",
    "}"
)
Write-Ok "settings_page.dart criado"

# -----------------------------------------------------------------------
# PASSO 5 - ABOUT FEATURE
# -----------------------------------------------------------------------
Write-Section "PASSO 5/6 - Gerando AboutPage"

# TechBadge widget
Write-Dart "$LIB\features\about\presentation\widgets\tech_badge.dart" @(
    "import 'package:flutter/material.dart';",
    "import '../../../../design_system/tokens/tokens.dart';",
    "",
    "class TechBadge extends StatelessWidget {",
    "  const TechBadge({super.key, required this.label, required this.color});",
    "  final String label;",
    "  final Color color;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Container(",
    "      padding: const EdgeInsets.symmetric(",
    "        horizontal: AppSpacing.sm,",
    "        vertical: AppSpacing.xxs,",
    "      ),",
    "      decoration: BoxDecoration(",
    "        color: color.withOpacity(0.12),",
    "        borderRadius: BorderRadius.circular(AppRadius.full),",
    "        border: Border.all(color: color.withOpacity(0.3)),",
    "      ),",
    "      child: Text(",
    "        label,",
    "        style: AppTextStyles.labelSmall.copyWith(",
    "          color: color,",
    "          fontWeight: FontWeight.w600,",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}"
)
Write-Ok "tech_badge.dart criado"

# AboutPage
Write-Dart "$LIB\features\about\presentation\pages\about_page.dart" @(
    "import 'package:flutter/material.dart';",
    "import 'package:flutter/services.dart';",
    "import '../../../../design_system/tokens/tokens.dart';",
    "import '../widgets/tech_badge.dart';",
    "",
    "class AboutPage extends StatelessWidget {",
    "  const AboutPage({super.key});",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final isDark = Theme.of(context).brightness == Brightness.dark;",
    "    final scheme = Theme.of(context).colorScheme;",
    "    final bgCard = isDark ? AppColors.dark800 : AppColors.white;",
    "    final border = isDark ? AppColors.dark600 : AppColors.neutral200;",
    "    final textPrimary = isDark ? AppColors.white : AppColors.neutral900;",
    "    final textMuted = isDark ? AppColors.neutral400 : AppColors.neutral600;",
    "",
    "    return Scaffold(",
    "      backgroundColor: isDark ? AppColors.dark900 : AppColors.neutral50,",
    "      appBar: AppBar(",
    "        title: Text(",
    "          'Sobre o App',",
    "          style: AppTextStyles.titleMedium.copyWith(color: textPrimary),",
    "        ),",
    "        backgroundColor: isDark ? AppColors.dark800 : AppColors.white,",
    "      ),",
    "      body: ListView(",
    "        padding: const EdgeInsets.all(AppSpacing.md),",
    "        children: [",
    "",
    "          // --- Hero card ---",
    "          Container(",
    "            width: double.infinity,",
    "            padding: const EdgeInsets.all(AppSpacing.xl),",
    "            decoration: BoxDecoration(",
    "              color: bgCard,",
    "              borderRadius: BorderRadius.circular(AppRadius.xl),",
    "              border: Border.all(color: border),",
    "            ),",
    "            child: Column(",
    "              children: [",
    "                // Logo",
    "                Container(",
    "                  width: 80,",
    "                  height: 80,",
    "                  decoration: BoxDecoration(",
    "                    color: scheme.primary.withOpacity(0.1),",
    "                    borderRadius: BorderRadius.circular(AppRadius.xl),",
    "                    border: Border.all(color: scheme.primary.withOpacity(0.3)),",
    "                  ),",
    "                  child: Center(",
    "                    child: CustomPaint(",
    "                      size: const Size(44, 44),",
    "                      painter: _MiniLogoPainter(color: scheme.primary),",
    "                    ),",
    "                  ),",
    "                ),",
    "                const SizedBox(height: AppSpacing.md),",
    "                Text(",
    "                  'EmersonX',",
    "                  style: AppTextStyles.headlineMedium.copyWith(",
    "                    color: textPrimary,",
    "                    fontWeight: FontWeight.w800,",
    "                  ),",
    "                ),",
    "                const SizedBox(height: AppSpacing.xxs),",
    "                Text(",
    "                  'Flutter Portfolio App',",
    "                  style: AppTextStyles.bodyMedium.copyWith(color: textMuted),",
    "                ),",
    "                const SizedBox(height: AppSpacing.sm),",
    "                // Versao - tap para copiar",
    "                GestureDetector(",
    "                  onTap: () {",
    "                    Clipboard.setData(const ClipboardData(text: '1.0.0+1'));",
    "                    ScaffoldMessenger.of(context).showSnackBar(",
    "                      const SnackBar(",
    "                        content: Text('Versao copiada!'),",
    "                        duration: Duration(seconds: 2),",
    "                      ),",
    "                    );",
    "                  },",
    "                  child: Container(",
    "                    padding: const EdgeInsets.symmetric(",
    "                      horizontal: AppSpacing.md,",
    "                      vertical: AppSpacing.xxs,",
    "                    ),",
    "                    decoration: BoxDecoration(",
    "                      color: scheme.primary.withOpacity(0.08),",
    "                      borderRadius: BorderRadius.circular(AppRadius.full),",
    "                    ),",
    "                    child: Text(",
    "                      'v1.0.0 (build 1)',",
    "                      style: AppTextStyles.labelSmall.copyWith(",
    "                        color: scheme.primary,",
    "                        fontWeight: FontWeight.w600,",
    "                      ),",
    "                    ),",
    "                  ),",
    "                ),",
    "              ],",
    "            ),",
    "          ),",
    "",
    "          const SizedBox(height: AppSpacing.md),",
    "",
    "          // --- Desenvolvedor ---",
    "          _InfoCard(",
    "            title: 'Desenvolvedor',",
    "            icon: Icons.person_outline,",
    "            isDark: isDark,",
    "            bgCard: bgCard,",
    "            border: border,",
    "            children: [",
    "              _InfoRow(label: 'Nome',  value: 'Emerson',           isDark: isDark),",
    "              _InfoRow(label: 'Stack', value: 'Flutter / Dart',    isDark: isDark),",
    "              _InfoRow(label: 'Foco',  value: 'Mobile & Frontend', isDark: isDark),",
    "            ],",
    "          ),",
    "",
    "          const SizedBox(height: AppSpacing.md),",
    "",
    "          // --- Arquitetura ---",
    "          _InfoCard(",
    "            title: 'Arquitetura',",
    "            icon: Icons.architecture,",
    "            isDark: isDark,",
    "            bgCard: bgCard,",
    "            border: border,",
    "            children: [",
    "              _InfoRow(label: 'Padrao',  value: 'Microapps + Clean Architecture', isDark: isDark),",
    "              _InfoRow(label: 'DI',      value: 'get_it + injectable',            isDark: isDark),",
    "              _InfoRow(label: 'Estado',  value: 'flutter_bloc + Cubit',           isDark: isDark),",
    "              _InfoRow(label: 'Rotas',   value: 'go_router',                     isDark: isDark),",
    "              _InfoRow(label: 'Backend', value: 'Firebase + REST APIs',           isDark: isDark),",
    "            ],",
    "          ),",
    "",
    "          const SizedBox(height: AppSpacing.md),",
    "",
    "          // --- Stack de tecnologias ---",
    "          Container(",
    "            width: double.infinity,",
    "            padding: const EdgeInsets.all(AppSpacing.md),",
    "            decoration: BoxDecoration(",
    "              color: bgCard,",
    "              borderRadius: BorderRadius.circular(AppRadius.lg),",
    "              border: Border.all(color: border),",
    "            ),",
    "            child: Column(",
    "              crossAxisAlignment: CrossAxisAlignment.start,",
    "              children: [",
    "                Row(",
    "                  children: [",
    "                    Icon(Icons.layers_outlined, size: 18, color: textMuted),",
    "                    const SizedBox(width: AppSpacing.xs),",
    "                    Text(",
    "                      'Stack de Tecnologias',",
    "                      style: AppTextStyles.labelLarge.copyWith(",
    "                        color: textPrimary, fontWeight: FontWeight.w600,",
    "                      ),",
    "                    ),",
    "                  ],",
    "                ),",
    "                const SizedBox(height: AppSpacing.md),",
    "                Wrap(",
    "                  spacing: AppSpacing.xs,",
    "                  runSpacing: AppSpacing.xs,",
    "                  children: [",
    "                    TechBadge(label: 'Flutter 3.x',        color: AppColors.moduleConnectivity),",
    "                    TechBadge(label: 'Dart 3.x',           color: AppColors.moduleConnectivity),",
    "                    TechBadge(label: 'flutter_bloc',       color: AppColors.moduleDesignSystem),",
    "                    TechBadge(label: 'go_router',          color: AppColors.moduleRouting),",
    "                    TechBadge(label: 'get_it',             color: AppColors.moduleDI),",
    "                    TechBadge(label: 'Firebase',           color: AppColors.moduleAnimations),",
    "                    TechBadge(label: 'Google Maps',        color: AppColors.moduleMaps),",
    "                    TechBadge(label: 'Gemini AI',          color: AppColors.moduleAI),",
    "                    TechBadge(label: 'Hive',               color: AppColors.moduleRegional),",
    "                    TechBadge(label: 'fpdart',             color: AppColors.moduleSensors),",
    "                    TechBadge(label: 'Rive',               color: AppColors.moduleAnimations),",
    "                    TechBadge(label: 'Lottie',             color: AppColors.moduleAnimations),",
    "                    TechBadge(label: 'mocktail',           color: AppColors.moduleTesting),",
    "                    TechBadge(label: 'bloc_test',          color: AppColors.moduleTesting),",
    "                    TechBadge(label: 'SOLID',              color: AppColors.success),",
    "                    TechBadge(label: 'Material 3',         color: AppColors.moduleSocial),",
    "                  ],",
    "                ),",
    "              ],",
    "            ),",
    "          ),",
    "",
    "          const SizedBox(height: AppSpacing.md),",
    "",
    "          // --- Modulos ---",
    "          _InfoCard(",
    "            title: 'Modulos',",
    "            icon: Icons.grid_view_rounded,",
    "            isDark: isDark,",
    "            bgCard: bgCard,",
    "            border: border,",
    "            children: [",
    "              _InfoRow(label: 'Total',        value: '14 modulos',      isDark: isDark),",
    "              _InfoRow(label: 'Telas',        value: '68+ telas',       isDark: isDark),",
    "              _InfoRow(label: 'Componentes',  value: 'Design System',   isDark: isDark),",
    "              _InfoRow(label: 'Cobertura',    value: 'Testes unitarios',isDark: isDark),",
    "            ],",
    "          ),",
    "",
    "          const SizedBox(height: AppSpacing.xxxl),",
    "",
    "          // Rodape",
    "          Center(",
    "            child: Text(",
    "              'Feito com Flutter por Emerson',",
    "              style: AppTextStyles.labelSmall.copyWith(color: textMuted),",
    "            ),",
    "          ),",
    "          const SizedBox(height: AppSpacing.lg),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "class _InfoCard extends StatelessWidget {",
    "  const _InfoCard({",
    "    required this.title,",
    "    required this.icon,",
    "    required this.isDark,",
    "    required this.bgCard,",
    "    required this.border,",
    "    required this.children,",
    "  });",
    "  final String title;",
    "  final IconData icon;",
    "  final bool isDark;",
    "  final Color bgCard;",
    "  final Color border;",
    "  final List<Widget> children;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final textPrimary = isDark ? AppColors.white : AppColors.neutral900;",
    "    final textMuted   = isDark ? AppColors.neutral400 : AppColors.neutral600;",
    "    return Container(",
    "      padding: const EdgeInsets.all(AppSpacing.md),",
    "      decoration: BoxDecoration(",
    "        color: bgCard,",
    "        borderRadius: BorderRadius.circular(AppRadius.lg),",
    "        border: Border.all(color: border),",
    "      ),",
    "      child: Column(",
    "        crossAxisAlignment: CrossAxisAlignment.start,",
    "        children: [",
    "          Row(",
    "            children: [",
    "              Icon(icon, size: 18, color: textMuted),",
    "              const SizedBox(width: AppSpacing.xs),",
    "              Text(",
    "                title,",
    "                style: AppTextStyles.labelLarge.copyWith(",
    "                  color: textPrimary, fontWeight: FontWeight.w600,",
    "                ),",
    "              ),",
    "            ],",
    "          ),",
    "          const SizedBox(height: AppSpacing.sm),",
    "          ...children.indexed.map((e) {",
    "            final i = e.$1;",
    "            final w = e.$2;",
    "            return Column(",
    "              children: [",
    "                if (i > 0) Divider(height: 1, color: border),",
    "                w,",
    "              ],",
    "            );",
    "          }),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "class _InfoRow extends StatelessWidget {",
    "  const _InfoRow({",
    "    required this.label,",
    "    required this.value,",
    "    required this.isDark,",
    "  });",
    "  final String label;",
    "  final String value;",
    "  final bool isDark;",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Padding(",
    "      padding: const EdgeInsets.symmetric(vertical: AppSpacing.xs),",
    "      child: Row(",
    "        children: [",
    "          Text(",
    "            label,",
    "            style: AppTextStyles.bodyMedium.copyWith(",
    "              color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "            ),",
    "          ),",
    "          const Spacer(),",
    "          Text(",
    "            value,",
    "            style: AppTextStyles.bodyMedium.copyWith(",
    "              color: isDark ? AppColors.white : AppColors.neutral900,",
    "              fontWeight: FontWeight.w500,",
    "            ),",
    "          ),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "}",
    "",
    "class _MiniLogoPainter extends CustomPainter {",
    "  const _MiniLogoPainter({required this.color});",
    "  final Color color;",
    "",
    "  @override",
    "  void paint(Canvas canvas, Size size) {",
    "    final p = Paint()",
    "      ..color = color",
    "      ..strokeWidth = 4",
    "      ..strokeCap = StrokeCap.round",
    "      ..style = PaintingStyle.stroke;",
    "    final w = size.width;",
    "    final h = size.height;",
    "    final e = Path()",
    "      ..moveTo(w * 0.05, h * 0.1)..lineTo(w * 0.05, h * 0.9)",
    "      ..moveTo(w * 0.05, h * 0.1)..lineTo(w * 0.38, h * 0.1)",
    "      ..moveTo(w * 0.05, h * 0.5)..lineTo(w * 0.32, h * 0.5)",
    "      ..moveTo(w * 0.05, h * 0.9)..lineTo(w * 0.38, h * 0.9);",
    "    canvas.drawPath(e, p);",
    "    canvas.drawLine(Offset(w * 0.52, h * 0.1), Offset(w * 0.95, h * 0.9), p);",
    "    canvas.drawLine(Offset(w * 0.95, h * 0.1), Offset(w * 0.52, h * 0.9), p);",
    "  }",
    "",
    "  @override",
    "  bool shouldRepaint(covariant CustomPainter o) => false;",
    "}"
)
Write-Ok "about_page.dart criado"

# -----------------------------------------------------------------------
# PASSO 6 - ATUALIZAR APPROUTER + HOMEPAGE ACTIONS
# -----------------------------------------------------------------------
Write-Section "PASSO 6/6 - Atualizando AppRouter e HomePage"

Write-Dart "$LIB\core\router\app_router.dart" @(
    "import 'package:flutter/material.dart';",
    "import 'package:go_router/go_router.dart';",
    "import '../../features/splash/presentation/pages/splash_page.dart';",
    "import '../../features/home/presentation/pages/home_page.dart';",
    "import '../../features/search/presentation/pages/search_page.dart';",
    "import '../../features/settings/presentation/pages/settings_page.dart';",
    "import '../../features/about/presentation/pages/about_page.dart';",
    "import 'app_routes.dart';",
    "",
    "final appRouter = GoRouter(",
    "  initialLocation: AppRoutes.splash,",
    "  debugLogDiagnostics: true,",
    "  routes: [",
    "",
    "    GoRoute(",
    "      path: AppRoutes.splash,",
    "      name: 'splash',",
    "      pageBuilder: (context, state) => _fade(state, const SplashPage()),",
    "    ),",
    "",
    "    GoRoute(",
    "      path: AppRoutes.home,",
    "      name: 'home',",
    "      pageBuilder: (context, state) => _slide(state, const HomePage()),",
    "    ),",
    "",
    "    GoRoute(",
    "      path: AppRoutes.search,",
    "      name: 'search',",
    "      pageBuilder: (context, state) => _bottomSlide(state, const SearchPage()),",
    "    ),",
    "",
    "    GoRoute(",
    "      path: AppRoutes.settings,",
    "      name: 'settings',",
    "      pageBuilder: (context, state) => _slide(state, const SettingsPage()),",
    "    ),",
    "",
    "    GoRoute(",
    "      path: AppRoutes.about,",
    "      name: 'about',",
    "      pageBuilder: (context, state) => _slide(state, const AboutPage()),",
    "    ),",
    "",
    "    // TODO: adicionar rotas dos modulos",
    "  ],",
    "",
    "  errorPageBuilder: (context, state) => MaterialPage(",
    "    child: Scaffold(",
    "      body: Center(",
    "        child: Column(",
    "          mainAxisAlignment: MainAxisAlignment.center,",
    "          children: [",
    "            const Icon(Icons.error_outline, size: 64, color: Colors.red),",
    "            const SizedBox(height: 16),",
    ('            Text(' + "'" + 'Rota nao encontrada: ' + '$' + '{state.uri}' + "'" + '),'),
    "            const SizedBox(height: 24),",
    "            ElevatedButton(",
    "              onPressed: () => context.go(AppRoutes.home),",
    "              child: const Text('Voltar ao inicio'),",
    "            ),",
    "          ],",
    "        ),",
    "      ),",
    "    ),",
    "  ),",
    ");",
    "",
    "// Transicoes",
    "CustomTransitionPage _fade(GoRouterState s, Widget child) =>",
    "  CustomTransitionPage(",
    "    key: s.pageKey, child: child,",
    "    transitionDuration: const Duration(milliseconds: 400),",
    "    transitionsBuilder: (_, anim, __, c) => FadeTransition(",
    "      opacity: CurvedAnimation(parent: anim, curve: Curves.easeInOut),",
    "      child: c,",
    "    ),",
    "  );",
    "",
    "CustomTransitionPage _slide(GoRouterState s, Widget child) =>",
    "  CustomTransitionPage(",
    "    key: s.pageKey, child: child,",
    "    transitionDuration: const Duration(milliseconds: 350),",
    "    transitionsBuilder: (_, anim, __, c) {",
    "      final tween = Tween(begin: const Offset(1, 0), end: Offset.zero)",
    "          .chain(CurveTween(curve: Curves.easeOutCubic));",
    "      return SlideTransition(",
    "        position: anim.drive(tween),",
    "        child: FadeTransition(",
    "          opacity: CurvedAnimation(parent: anim, curve: Curves.easeOut),",
    "          child: c,",
    "        ),",
    "      );",
    "    },",
    "  );",
    "",
    "CustomTransitionPage _bottomSlide(GoRouterState s, Widget child) =>",
    "  CustomTransitionPage(",
    "    key: s.pageKey, child: child,",
    "    transitionDuration: const Duration(milliseconds: 350),",
    "    transitionsBuilder: (_, anim, __, c) {",
    "      final tween = Tween(begin: const Offset(0, 0.06), end: Offset.zero)",
    "          .chain(CurveTween(curve: Curves.easeOutCubic));",
    "      return SlideTransition(",
    "        position: anim.drive(tween),",
    "        child: FadeTransition(",
    "          opacity: CurvedAnimation(parent: anim, curve: Curves.easeOut),",
    "          child: c,",
    "        ),",
    "      );",
    "    },",
    "  );"
)
Write-Ok "app_router.dart atualizado com 5 rotas"

# Atualiza HomePage com os 3 botoes na AppBar
Write-Dart "$LIB\features\home\presentation\pages\home_page.dart" @(
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_bloc/flutter_bloc.dart';",
    "import 'package:go_router/go_router.dart';",
    "import '../../../../design_system/tokens/tokens.dart';",
    "import '../../../../core/di/theme_cubit.dart';",
    "import '../../../../core/router/app_routes.dart';",
    "import '../cubit/home_cubit.dart';",
    "import '../cubit/home_state.dart';",
    "import '../widgets/module_card.dart';",
    "",
    "class HomePage extends StatelessWidget {",
    "  const HomePage({super.key});",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return BlocProvider(",
    "      create: (_) => HomeCubit()..loadModules(),",
    "      child: const _HomeView(),",
    "    );",
    "  }",
    "}",
    "",
    "class _HomeView extends StatelessWidget {",
    "  const _HomeView();",
    "",
    "  int _columns(double width) {",
    "    if (width < 600) return 2;",
    "    if (width < 900) return 3;",
    "    if (width < 1200) return 4;",
    "    return 5;",
    "  }",
    "",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final width  = MediaQuery.sizeOf(context).width;",
    "    final isDark = Theme.of(context).brightness == Brightness.dark;",
    "    final cols   = _columns(width);",
    "",
    "    return Scaffold(",
    "      body: CustomScrollView(",
    "        slivers: [",
    "",
    "          SliverAppBar(",
    "            pinned: true,",
    "            expandedHeight: 130,",
    "            backgroundColor: isDark ? AppColors.dark800 : AppColors.white,",
    "            flexibleSpace: FlexibleSpaceBar(",
    "              titlePadding: const EdgeInsets.fromLTRB(20, 0, 20, 14),",
    "              title: Column(",
    "                mainAxisAlignment: MainAxisAlignment.end,",
    "                crossAxisAlignment: CrossAxisAlignment.start,",
    "                children: [",
    "                  Text(",
    "                    _greeting(),",
    "                    style: AppTextStyles.labelSmall.copyWith(",
    "                      color: isDark ? AppColors.neutral400 : AppColors.neutral600,",
    "                    ),",
    "                  ),",
    "                  Text(",
    "                    'EmersonX',",
    "                    style: AppTextStyles.headlineMedium.copyWith(",
    "                      color: isDark ? AppColors.white : AppColors.neutral900,",
    "                      fontWeight: FontWeight.w800,",
    "                    ),",
    "                  ),",
    "                ],",
    "              ),",
    "              background: Container(",
    "                color: isDark ? AppColors.dark800 : AppColors.white,",
    "              ),",
    "            ),",
    "            actions: [",
    "              // Busca",
    "              IconButton(",
    "                icon: const Icon(Icons.search_rounded),",
    "                tooltip: 'Buscar',",
    "                onPressed: () => context.push(AppRoutes.search),",
    "              ),",
    "              // Toggle tema",
    "              BlocBuilder<ThemeCubit, ThemeMode>(",
    "                builder: (context, mode) => IconButton(",
    "                  icon: Icon(",
    "                    mode == ThemeMode.dark",
    "                        ? Icons.light_mode_outlined",
    "                        : Icons.dark_mode_outlined,",
    "                  ),",
    "                  tooltip: 'Alternar tema',",
    "                  onPressed: () => context.read<ThemeCubit>().toggle(),",
    "                ),",
    "              ),",
    "              // Menu (settings + about)",
    "              PopupMenuButton<String>(",
    "                icon: const Icon(Icons.more_vert_rounded),",
    "                onSelected: (v) => context.push(v),",
    "                itemBuilder: (_) => [",
    "                  const PopupMenuItem(",
    "                    value: AppRoutes.settings,",
    "                    child: ListTile(",
    "                      leading: Icon(Icons.settings_outlined),",
    "                      title: Text('Configuracoes'),",
    "                      contentPadding: EdgeInsets.zero,",
    "                      dense: true,",
    "                    ),",
    "                  ),",
    "                  const PopupMenuItem(",
    "                    value: AppRoutes.about,",
    "                    child: ListTile(",
    "                      leading: Icon(Icons.info_outline),",
    "                      title: Text('Sobre o App'),",
    "                      contentPadding: EdgeInsets.zero,",
    "                      dense: true,",
    "                    ),",
    "                  ),",
    "                ],",
    "              ),",
    "              const SizedBox(width: AppSpacing.xs),",
    "            ],",
    "          ),",
    "",
    "          SliverPadding(",
    "            padding: const EdgeInsets.fromLTRB(20, 20, 20, 8),",
    "            sliver: SliverToBoxAdapter(",
    "              child: BlocBuilder<HomeCubit, HomeState>(",
    "                builder: (context, state) {",
    "                  final count = state is HomeLoaded ? state.modules.length : 0;",
    "                  return Row(",
    "                    children: [",
    "                      Text(",
    "                        'Modulos',",
    "                        style: AppTextStyles.titleMedium.copyWith(",
    "                          color: isDark ? AppColors.white : AppColors.neutral900,",
    "                        ),",
    "                      ),",
    "                      const SizedBox(width: AppSpacing.xs),",
    "                      Container(",
    "                        padding: const EdgeInsets.symmetric(",
    "                          horizontal: AppSpacing.xs, vertical: AppSpacing.xxxs,",
    "                        ),",
    "                        decoration: BoxDecoration(",
    "                          color: AppColors.primary.withOpacity(0.1),",
    "                          borderRadius: BorderRadius.circular(AppRadius.full),",
    "                        ),",
    "                        child: Text(",
    "                          '$count',",
    "                          style: AppTextStyles.labelSmall.copyWith(",
    "                            color: AppColors.primary,",
    "                            fontWeight: FontWeight.w700,",
    "                          ),",
    "                        ),",
    "                      ),",
    "                    ],",
    "                  );",
    "                },",
    "              ),",
    "            ),",
    "          ),",
    "",
    "          BlocBuilder<HomeCubit, HomeState>(",
    "            builder: (context, state) {",
    "              if (state is HomeLoading) {",
    "                return SliverPadding(",
    "                  padding: const EdgeInsets.fromLTRB(20, 0, 20, 32),",
    "                  sliver: SliverGrid(",
    "                    delegate: SliverChildBuilderDelegate(",
    "                      (_, __) => _ShimmerCard(isDark: isDark),",
    "                      childCount: 8,",
    "                    ),",
    "                    gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(",
    "                      crossAxisCount: cols,",
    "                      crossAxisSpacing: AppSpacing.sm,",
    "                      mainAxisSpacing: AppSpacing.sm,",
    "                      childAspectRatio: 0.85,",
    "                    ),",
    "                  ),",
    "                );",
    "              }",
    "              if (state is HomeLoaded) {",
    "                return SliverPadding(",
    "                  padding: const EdgeInsets.fromLTRB(20, 0, 20, 32),",
    "                  sliver: SliverGrid(",
    "                    delegate: SliverChildBuilderDelegate(",
    "                      (context, i) {",
    "                        final mod = state.modules[i];",
    "                        return ModuleCard(",
    "                          module: mod,",
    "                          onTap: () => context.go(mod.route),",
    "                        );",
    "                      },",
    "                      childCount: state.modules.length,",
    "                    ),",
    "                    gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(",
    "                      crossAxisCount: cols,",
    "                      crossAxisSpacing: AppSpacing.sm,",
    "                      mainAxisSpacing: AppSpacing.sm,",
    "                      childAspectRatio: 0.85,",
    "                    ),",
    "                  ),",
    "                );",
    "              }",
    "              return const SliverToBoxAdapter(child: SizedBox.shrink());",
    "            },",
    "          ),",
    "        ],",
    "      ),",
    "    );",
    "  }",
    "",
    "  String _greeting() {",
    "    final h = DateTime.now().hour;",
    "    if (h < 12) return 'Bom dia, Emerson';",
    "    if (h < 18) return 'Boa tarde, Emerson';",
    "    return 'Boa noite, Emerson';",
    "  }",
    "}",
    "",
    "class _ShimmerCard extends StatefulWidget {",
    "  const _ShimmerCard({required this.isDark});",
    "  final bool isDark;",
    "  @override",
    "  State<_ShimmerCard> createState() => _ShimmerCardState();",
    "}",
    "",
    "class _ShimmerCardState extends State<_ShimmerCard>",
    "    with SingleTickerProviderStateMixin {",
    "  late AnimationController _ctrl;",
    "  late Animation<double> _anim;",
    "",
    "  @override",
    "  void initState() {",
    "    super.initState();",
    "    _ctrl = AnimationController(",
    "      vsync: this, duration: const Duration(milliseconds: 1000),",
    "    )..repeat(reverse: true);",
    "    _anim = CurvedAnimation(parent: _ctrl, curve: Curves.easeInOut);",
    "  }",
    "",
    "  @override",
    "  void dispose() { _ctrl.dispose(); super.dispose(); }",
    "",
    "  @override",
    "  Widget build(BuildContext context) => FadeTransition(",
    "    opacity: Tween(begin: 0.4, end: 0.9).animate(_anim),",
    "    child: Container(",
    "      decoration: BoxDecoration(",
    "        color: widget.isDark ? AppColors.dark700 : AppColors.neutral100,",
    "        borderRadius: BorderRadius.circular(AppRadius.lg),",
    "      ),",
    "    ),",
    "  );",
    "}"
)
Write-Ok "home_page.dart atualizado (busca + menu na AppBar)"

# -----------------------------------------------------------------------
# RESUMO
# -----------------------------------------------------------------------
Write-Host ""
Write-Host "  ==================================================" -ForegroundColor Green
Write-Host "   FASE 3 CONCLUIDA!" -ForegroundColor Green
Write-Host "  ==================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Arquivos criados / atualizados:" -ForegroundColor White
Write-Host ""
Write-Host "  [NOVO] features/search/                  " -ForegroundColor Green
Write-Host "         domain/entities/search_result.dart" -ForegroundColor DarkGray
Write-Host "         data/datasources/search_index.dart" -ForegroundColor DarkGray
Write-Host "         presentation/cubit/search_cubit   " -ForegroundColor DarkGray
Write-Host "         presentation/widgets/result_tile  " -ForegroundColor DarkGray
Write-Host "         presentation/pages/search_page    " -ForegroundColor DarkGray
Write-Host ""
Write-Host "  [NOVO] features/settings/                " -ForegroundColor Green
Write-Host "         domain/entities/app_settings      " -ForegroundColor DarkGray
Write-Host "         presentation/cubit/settings_cubit " -ForegroundColor DarkGray
Write-Host "         presentation/widgets/settings_tile" -ForegroundColor DarkGray
Write-Host "         presentation/pages/settings_page  " -ForegroundColor DarkGray
Write-Host ""
Write-Host "  [NOVO] features/about/                   " -ForegroundColor Green
Write-Host "         presentation/widgets/tech_badge   " -ForegroundColor DarkGray
Write-Host "         presentation/pages/about_page     " -ForegroundColor DarkGray
Write-Host ""
Write-Host "  [UPD]  core/router/app_routes.dart       " -ForegroundColor Yellow
Write-Host "  [UPD]  core/router/app_router.dart       " -ForegroundColor Yellow
Write-Host "  [UPD]  features/home/presentation/pages/ " -ForegroundColor Yellow
Write-Host ""
Write-Host "  Navegacao:" -ForegroundColor White
Write-Host "  Home AppBar --> [busca] [tema] [menu ...]" -ForegroundColor Cyan
Write-Host "  menu --> Configuracoes (/settings)" -ForegroundColor Cyan
Write-Host "  menu --> Sobre (/about)" -ForegroundColor Cyan
Write-Host "  [busca] --> SearchPage (/search)" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Para rodar:" -ForegroundColor White
Write-Host "  flutter pub get" -ForegroundColor Cyan
Write-Host "  flutter run" -ForegroundColor Cyan
Write-Host ""
