// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5b0LPjuXp2wprAXQSh_Dei0HfJT47p0k',
    appId: '1:305334315037:web:a3315b63d3cb6b67bfbef4',
    messagingSenderId: '305334315037',
    projectId: 'ecommerce-white-label-fe9d1',
    authDomain: 'ecommerce-white-label-fe9d1.firebaseapp.com',
    storageBucket: 'ecommerce-white-label-fe9d1.firebasestorage.app',
    measurementId: 'G-X43BE4HXVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKjML331LZ3Elk0-K_Rz6-p9M6Eal2L4',
    appId: '1:305334315037:android:0ab406eedff92985bfbef4',
    messagingSenderId: '305334315037',
    projectId: 'ecommerce-white-label-fe9d1',
    storageBucket: 'ecommerce-white-label-fe9d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdVfZAD0Yz3_fCYKC4SITvpmg1NkCG8Hg',
    appId: '1:305334315037:ios:0fbfed2f16f0ca42bfbef4',
    messagingSenderId: '305334315037',
    projectId: 'ecommerce-white-label-fe9d1',
    storageBucket: 'ecommerce-white-label-fe9d1.firebasestorage.app',
    androidClientId: '305334315037-tqt06mj50m9jm1qb2l8fo04ddjqvs0jo.apps.googleusercontent.com',
    iosClientId: '305334315037-85on5fgb548gnm5hhc2vtpk3lhu3qagb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdVfZAD0Yz3_fCYKC4SITvpmg1NkCG8Hg',
    appId: '1:305334315037:ios:0fbfed2f16f0ca42bfbef4',
    messagingSenderId: '305334315037',
    projectId: 'ecommerce-white-label-fe9d1',
    storageBucket: 'ecommerce-white-label-fe9d1.firebasestorage.app',
    androidClientId: '305334315037-tqt06mj50m9jm1qb2l8fo04ddjqvs0jo.apps.googleusercontent.com',
    iosClientId: '305334315037-85on5fgb548gnm5hhc2vtpk3lhu3qagb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5b0LPjuXp2wprAXQSh_Dei0HfJT47p0k',
    appId: '1:305334315037:web:002109fc9023f7ddbfbef4',
    messagingSenderId: '305334315037',
    projectId: 'ecommerce-white-label-fe9d1',
    authDomain: 'ecommerce-white-label-fe9d1.firebaseapp.com',
    storageBucket: 'ecommerce-white-label-fe9d1.firebasestorage.app',
    measurementId: 'G-1M9NSKQVHZ',
  );
}
